spring.application.name=smart-exam-seating-arrangement

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/smart_exam_seating
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true